// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Company.proto

package com.cssiot.entity;

public final class Company {
  private Company() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface innerClassOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cssiot.entity.innerClass)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string registrationNum = 1;</code>
     */
    boolean hasRegistrationNum();
    /**
     * <code>required string registrationNum = 1;</code>
     */
    java.lang.String getRegistrationNum();
    /**
     * <code>required string registrationNum = 1;</code>
     */
    com.google.protobuf.ByteString
        getRegistrationNumBytes();

    /**
     * <code>optional string companyName = 2;</code>
     */
    boolean hasCompanyName();
    /**
     * <code>optional string companyName = 2;</code>
     */
    java.lang.String getCompanyName();
    /**
     * <code>optional string companyName = 2;</code>
     */
    com.google.protobuf.ByteString
        getCompanyNameBytes();

    /**
     * <code>optional string companyAddress = 3;</code>
     */
    boolean hasCompanyAddress();
    /**
     * <code>optional string companyAddress = 3;</code>
     */
    java.lang.String getCompanyAddress();
    /**
     * <code>optional string companyAddress = 3;</code>
     */
    com.google.protobuf.ByteString
        getCompanyAddressBytes();

    /**
     * <code>repeated string companyStaff = 4;</code>
     */
    com.google.protobuf.ProtocolStringList
        getCompanyStaffList();
    /**
     * <code>repeated string companyStaff = 4;</code>
     */
    int getCompanyStaffCount();
    /**
     * <code>repeated string companyStaff = 4;</code>
     */
    java.lang.String getCompanyStaff(int index);
    /**
     * <code>repeated string companyStaff = 4;</code>
     */
    com.google.protobuf.ByteString
        getCompanyStaffBytes(int index);
  }
  /**
   * Protobuf type {@code com.cssiot.entity.innerClass}
   */
  public static final class innerClass extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.cssiot.entity.innerClass)
      innerClassOrBuilder {
    // Use innerClass.newBuilder() to construct.
    private innerClass(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private innerClass(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final innerClass defaultInstance;
    public static innerClass getDefaultInstance() {
      return defaultInstance;
    }

    public innerClass getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private innerClass(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              registrationNum_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              companyName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              companyAddress_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                companyStaff_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              companyStaff_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          companyStaff_ = companyStaff_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cssiot.entity.Company.internal_static_com_cssiot_entity_innerClass_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cssiot.entity.Company.internal_static_com_cssiot_entity_innerClass_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cssiot.entity.Company.innerClass.class, com.cssiot.entity.Company.innerClass.Builder.class);
    }

    public static com.google.protobuf.Parser<innerClass> PARSER =
        new com.google.protobuf.AbstractParser<innerClass>() {
      public innerClass parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new innerClass(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<innerClass> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int REGISTRATIONNUM_FIELD_NUMBER = 1;
    private java.lang.Object registrationNum_;
    /**
     * <code>required string registrationNum = 1;</code>
     */
    public boolean hasRegistrationNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string registrationNum = 1;</code>
     */
    public java.lang.String getRegistrationNum() {
      java.lang.Object ref = registrationNum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          registrationNum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string registrationNum = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRegistrationNumBytes() {
      java.lang.Object ref = registrationNum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        registrationNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANYNAME_FIELD_NUMBER = 2;
    private java.lang.Object companyName_;
    /**
     * <code>optional string companyName = 2;</code>
     */
    public boolean hasCompanyName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string companyName = 2;</code>
     */
    public java.lang.String getCompanyName() {
      java.lang.Object ref = companyName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          companyName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string companyName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyNameBytes() {
      java.lang.Object ref = companyName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANYADDRESS_FIELD_NUMBER = 3;
    private java.lang.Object companyAddress_;
    /**
     * <code>optional string companyAddress = 3;</code>
     */
    public boolean hasCompanyAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string companyAddress = 3;</code>
     */
    public java.lang.String getCompanyAddress() {
      java.lang.Object ref = companyAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          companyAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string companyAddress = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyAddressBytes() {
      java.lang.Object ref = companyAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANYSTAFF_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList companyStaff_;
    /**
     * <code>repeated string companyStaff = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCompanyStaffList() {
      return companyStaff_;
    }
    /**
     * <code>repeated string companyStaff = 4;</code>
     */
    public int getCompanyStaffCount() {
      return companyStaff_.size();
    }
    /**
     * <code>repeated string companyStaff = 4;</code>
     */
    public java.lang.String getCompanyStaff(int index) {
      return companyStaff_.get(index);
    }
    /**
     * <code>repeated string companyStaff = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyStaffBytes(int index) {
      return companyStaff_.getByteString(index);
    }

    private void initFields() {
      registrationNum_ = "";
      companyName_ = "";
      companyAddress_ = "";
      companyStaff_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRegistrationNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRegistrationNumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCompanyNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCompanyAddressBytes());
      }
      for (int i = 0; i < companyStaff_.size(); i++) {
        output.writeBytes(4, companyStaff_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRegistrationNumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCompanyNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCompanyAddressBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < companyStaff_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(companyStaff_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCompanyStaffList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cssiot.entity.Company.innerClass parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cssiot.entity.Company.innerClass parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cssiot.entity.Company.innerClass parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cssiot.entity.Company.innerClass parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cssiot.entity.Company.innerClass parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cssiot.entity.Company.innerClass parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cssiot.entity.Company.innerClass parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cssiot.entity.Company.innerClass parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cssiot.entity.Company.innerClass parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cssiot.entity.Company.innerClass parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cssiot.entity.Company.innerClass prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cssiot.entity.innerClass}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cssiot.entity.innerClass)
        com.cssiot.entity.Company.innerClassOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cssiot.entity.Company.internal_static_com_cssiot_entity_innerClass_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cssiot.entity.Company.internal_static_com_cssiot_entity_innerClass_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cssiot.entity.Company.innerClass.class, com.cssiot.entity.Company.innerClass.Builder.class);
      }

      // Construct using com.cssiot.entity.Company.innerClass.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        registrationNum_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        companyName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        companyAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        companyStaff_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cssiot.entity.Company.internal_static_com_cssiot_entity_innerClass_descriptor;
      }

      public com.cssiot.entity.Company.innerClass getDefaultInstanceForType() {
        return com.cssiot.entity.Company.innerClass.getDefaultInstance();
      }

      public com.cssiot.entity.Company.innerClass build() {
        com.cssiot.entity.Company.innerClass result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cssiot.entity.Company.innerClass buildPartial() {
        com.cssiot.entity.Company.innerClass result = new com.cssiot.entity.Company.innerClass(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.registrationNum_ = registrationNum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.companyName_ = companyName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.companyAddress_ = companyAddress_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          companyStaff_ = companyStaff_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.companyStaff_ = companyStaff_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cssiot.entity.Company.innerClass) {
          return mergeFrom((com.cssiot.entity.Company.innerClass)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cssiot.entity.Company.innerClass other) {
        if (other == com.cssiot.entity.Company.innerClass.getDefaultInstance()) return this;
        if (other.hasRegistrationNum()) {
          bitField0_ |= 0x00000001;
          registrationNum_ = other.registrationNum_;
          onChanged();
        }
        if (other.hasCompanyName()) {
          bitField0_ |= 0x00000002;
          companyName_ = other.companyName_;
          onChanged();
        }
        if (other.hasCompanyAddress()) {
          bitField0_ |= 0x00000004;
          companyAddress_ = other.companyAddress_;
          onChanged();
        }
        if (!other.companyStaff_.isEmpty()) {
          if (companyStaff_.isEmpty()) {
            companyStaff_ = other.companyStaff_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureCompanyStaffIsMutable();
            companyStaff_.addAll(other.companyStaff_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRegistrationNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cssiot.entity.Company.innerClass parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cssiot.entity.Company.innerClass) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object registrationNum_ = "";
      /**
       * <code>required string registrationNum = 1;</code>
       */
      public boolean hasRegistrationNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string registrationNum = 1;</code>
       */
      public java.lang.String getRegistrationNum() {
        java.lang.Object ref = registrationNum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            registrationNum_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string registrationNum = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRegistrationNumBytes() {
        java.lang.Object ref = registrationNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          registrationNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string registrationNum = 1;</code>
       */
      public Builder setRegistrationNum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        registrationNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string registrationNum = 1;</code>
       */
      public Builder clearRegistrationNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        registrationNum_ = getDefaultInstance().getRegistrationNum();
        onChanged();
        return this;
      }
      /**
       * <code>required string registrationNum = 1;</code>
       */
      public Builder setRegistrationNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        registrationNum_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object companyName_ = "";
      /**
       * <code>optional string companyName = 2;</code>
       */
      public boolean hasCompanyName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string companyName = 2;</code>
       */
      public java.lang.String getCompanyName() {
        java.lang.Object ref = companyName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            companyName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string companyName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCompanyNameBytes() {
        java.lang.Object ref = companyName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          companyName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string companyName = 2;</code>
       */
      public Builder setCompanyName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        companyName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string companyName = 2;</code>
       */
      public Builder clearCompanyName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        companyName_ = getDefaultInstance().getCompanyName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string companyName = 2;</code>
       */
      public Builder setCompanyNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        companyName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object companyAddress_ = "";
      /**
       * <code>optional string companyAddress = 3;</code>
       */
      public boolean hasCompanyAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string companyAddress = 3;</code>
       */
      public java.lang.String getCompanyAddress() {
        java.lang.Object ref = companyAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            companyAddress_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string companyAddress = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCompanyAddressBytes() {
        java.lang.Object ref = companyAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          companyAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string companyAddress = 3;</code>
       */
      public Builder setCompanyAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        companyAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string companyAddress = 3;</code>
       */
      public Builder clearCompanyAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        companyAddress_ = getDefaultInstance().getCompanyAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string companyAddress = 3;</code>
       */
      public Builder setCompanyAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        companyAddress_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList companyStaff_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCompanyStaffIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          companyStaff_ = new com.google.protobuf.LazyStringArrayList(companyStaff_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string companyStaff = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getCompanyStaffList() {
        return companyStaff_.getUnmodifiableView();
      }
      /**
       * <code>repeated string companyStaff = 4;</code>
       */
      public int getCompanyStaffCount() {
        return companyStaff_.size();
      }
      /**
       * <code>repeated string companyStaff = 4;</code>
       */
      public java.lang.String getCompanyStaff(int index) {
        return companyStaff_.get(index);
      }
      /**
       * <code>repeated string companyStaff = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCompanyStaffBytes(int index) {
        return companyStaff_.getByteString(index);
      }
      /**
       * <code>repeated string companyStaff = 4;</code>
       */
      public Builder setCompanyStaff(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyStaffIsMutable();
        companyStaff_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string companyStaff = 4;</code>
       */
      public Builder addCompanyStaff(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyStaffIsMutable();
        companyStaff_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string companyStaff = 4;</code>
       */
      public Builder addAllCompanyStaff(
          java.lang.Iterable<java.lang.String> values) {
        ensureCompanyStaffIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, companyStaff_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string companyStaff = 4;</code>
       */
      public Builder clearCompanyStaff() {
        companyStaff_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string companyStaff = 4;</code>
       */
      public Builder addCompanyStaffBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyStaffIsMutable();
        companyStaff_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.cssiot.entity.innerClass)
    }

    static {
      defaultInstance = new innerClass(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.cssiot.entity.innerClass)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cssiot_entity_innerClass_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cssiot_entity_innerClass_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCompany.proto\022\021com.cssiot.entity\"h\n\nin" +
      "nerClass\022\027\n\017registrationNum\030\001 \002(\t\022\023\n\013com" +
      "panyName\030\002 \001(\t\022\026\n\016companyAddress\030\003 \001(\t\022\024" +
      "\n\014companyStaff\030\004 \003(\tB\034\n\021com.cssiot.entit" +
      "yB\007Company"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_cssiot_entity_innerClass_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cssiot_entity_innerClass_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_cssiot_entity_innerClass_descriptor,
        new java.lang.String[] { "RegistrationNum", "CompanyName", "CompanyAddress", "CompanyStaff", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
